
Pitts30k_root = "/home/oliver/datasets_drive/vpr_datasets/Pittsburgh-Query"
Essex3in1_root = "/home/oliver/datasets_drive/vpr_datasets/ESSEX3IN1_dataset"
Tokyo247_root = "/home/oliver/datasets_drive/vpr_datasets/tokyo247"
MSLS_root = "/home/oliver/datasets_drive/vpr_datasets/msls"
SFXL_root = "/home/oliver/datasets_drive/vpr_datasets/sf_xl"
SVOX_root = "/home/oliver/datasets_drive/vpr_datasets/svox"
"""

Pitts30k_root = "/Users/olivergrainge/Documents/github/Datasets/Pittsburgh-Query"
Essex3in1_root = "/Users/olivergrainge/Documents/github/Datasets/ESSEX3IN1_dataset"
Tokyo247_root = ""
MSLS_root = ""
SFXL_root = ""
"""